import type { Metadata } from "next";
import "./globals.css";

import {Inter} from "next/font/google";

const _font = Inter({
  weight: '400',
  subsets: ['latin'],
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const font= _font.className;

  return (
    <html lang="en">
      <body
        className={`${font}  antialiased flex flex-col min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
